---
title: "126 Data Project, Step 2"
date: "Sam Ream, Valeria Lopez, Skyler Yee"
output:
  pdf_document:
    latex_engine: xelatex
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
# knit options
knitr::opts_chunk$set(echo = F,
                      results = 'markup',
                      fig.width = 4,
                      fig.height = 3,
                      fig.align = 'center',
                      message = F,
                      warning = F)

# packages
library(tidyverse)
library(faraway)
library(RSQLite)
library(skimr)
library(GGally)
library(tidymodels)
library(leaps)
```

```{r, echo=FALSE}
ball <- dbConnect(drv=RSQLite::SQLite(), dbname="../../data/database.sqlite")
```

```{r, echo =FALSE}
batting <- dbGetQuery(ball, "
                            SELECT
                            sum(ab) AS AT_BAT,
                            player_id,
                            sum(r) AS RUNS,
                            sum(hr) AS HOME_RUNS, 
                            sum(triple) AS TRIPLE,
                            sum(double) AS DOUBLE,
                            (sum(h) -  sum(hr) - sum(triple) - sum(double)) AS SINGLES,
                            sum(bb) AS WALKS,
                            sum(ibb) AS INT_WALKS,
                            sum(sb) AS STOLEN_BASES,
                            sum(hbp) AS HIT_BY_PITCH
                            
                            FROM
                            batting
                            where
                            year > 2000
                            group by
                            player_id
                            
                   ")
sumbat <- batting
batting <- subset(batting,batting[,1]>100)


for (x in 3:11) 
{
  batting[,x] <- batting[,x] / 1
}

set.seed(5)
batting <- sample_n(batting, 500, replace = FALSE)

players <- dbGetQuery(ball, "
                      
                      SELECT 
                      player_id,
                      (weight / POWER(height, 2)) *703 AS BMI,
                      bats as HAND
                      FROM
                      player
                      
                      ")




players <- subset(players, players[,2]>0)



for ( x in 1:17918)
{
  if(players[x,2] <= 18.5) {players[x,2] <- "U"} 
  else if(players[x,2] <= 24.9) {players[x,2] <- "H"}
  else if(players[x,2] <= 29.9) {players[x,2] <- "O"}
  else {players[x,2] <- "B"}
}

batting <-  merge(batting, players, by="player_id" )
```

# Sam

# Valeria

```{r}
lm(RUNS~INT_WALKS + SINGLES + TRIPLE + STOLEN_BASES + HOME_RUNS, data = batting) %>% tidy()
```

```{r}
lm(RUNS~SINGLES + TRIPLE + HOME_RUNS, data = batting) %>% tidy()
```

```{r}
stat_model <- regsubsets(RUNS~HOME_RUNS + TRIPLE + DOUBLE + SINGLES + WALKS + INT_WALKS + STOLEN_BASES + HIT_BY_PITCH, data = batting,
                  method = 'seqrep',
                  nbest = 1,
                  nvmax = 4)
summary(stat_model)
```

We used a stepwise search to create the best model for our data. For a size of 4 predictors the variables home runs, singles, walks, and stolen bases create a well fit model. Our adjusted R^2 is .9925. 


## Stat model residual plot

```{r}
stat_model <- lm(RUNS~HOME_RUNS + SINGLES + WALKS + STOLEN_BASES, data = batting)
res <- resid(stat_model)
plot(fitted(stat_model), res, ylab = 'Residuals', xlab = 'Fitted Model')
abline(0,0)
```
```{r}
summary(lm(RUNS~HOME_RUNS + SINGLES + WALKS + STOLEN_BASES, data = batting))
```


## CI 
```{r}
chosen_model <- lm(RUNS~ HOME_RUNS + SINGLES + WALKS + STOLEN_BASES, data = batting)
```

```{r}
confint(chosen_model, level = 0.95)
```

```{r}
x_bar <- batting %>% select(HOME_RUNS, SINGLES, WALKS, STOLEN_BASES) %>% summarize(across(everything(), mean))
x_bar
```

```{r}
predict(chosen_model, newdata = x_bar, interval = 'confidence', level = 0.95)
```
With 95% confidence, the mean predicted value is estimated to be between 204.71 and 208.50.



## PI
```{r}
x_jeremy <- data.frame(200)
colnames(x_jeremy) <- "DOUBLE"
x_jeremy


batting <- batting %>% slice(-as.numeric(rownames(x_jeremy)))
```

```{r}
predict(chosen_model, newdata = , interval = 'prediction', level = 0.95)
```
With 95% confidence, the 

# Skyler
